"""Added candle session

Revision ID: 0c951187556d
Revises: a48f0317218a
Create Date: 2025-08-04 15:21:13.824963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c951187556d'
down_revision = 'a48f0317218a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candle', schema=None) as batch_op:
        batch_op.drop_column('session')

    # ### end Alembic commands ###
