"""Added locates to trades and executions

Revision ID: 1d3e6b5ad941
Revises: b9fa184ee37f
Create Date: 2025-11-26 13:00:57.124741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3e6b5ad941'
down_revision = 'b9fa184ee37f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locates', sa.Float(), nullable=True))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locates', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('locates')

    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_column('locates')

    # ### end Alembic commands ###
