"""Added ECN fee to transactions

Revision ID: 76c6ed2ba817
Revises: 7da286bfa3cf
Create Date: 2025-11-25 13:41:17.411413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c6ed2ba817'
down_revision = '7da286bfa3cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ecn_fee', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('ecn_fee')

    # ### end Alembic commands ###
