"""Added the risk table

Revision ID: 7da286bfa3cf
Revises: 7e00a5ee1791
Create Date: 2025-11-22 18:18:24.171547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da286bfa3cf'
down_revision = '7e00a5ee1791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.alter_column('show_r',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.alter_column('show_r',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
