"""Added the risk show option in user settings

Revision ID: 7e00a5ee1791
Revises: 4c482c14afe7
Create Date: 2025-11-22 18:14:48.429639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e00a5ee1791'
down_revision = '4c482c14afe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_r', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.drop_column('show_r')

    # ### end Alembic commands ###
