"""Added properties to watchlist entries

Revision ID: 99e9a6190e41
Revises: 0c951187556d
Create Date: 2025-08-11 19:54:28.138204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e9a6190e41'
down_revision = '0c951187556d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_cap', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('float_shares', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('per', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('eps', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('exchange', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sector', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('industry', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_entry', schema=None) as batch_op:
        batch_op.drop_column('country')
        batch_op.drop_column('industry')
        batch_op.drop_column('sector')
        batch_op.drop_column('exchange')
        batch_op.drop_column('eps')
        batch_op.drop_column('per')
        batch_op.drop_column('float_shares')
        batch_op.drop_column('market_cap')

    # ### end Alembic commands ###
