"""Added the user management

Revision ID: a48f0317218a
Revises: 4f748d7c4d95
Create Date: 2025-07-30 10:46:29.610747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a48f0317218a'
down_revision = '4f748d7c4d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('balance_user_rel', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('error', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('error_user_rel', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('setting_user_rel', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('strategy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('strategy_user_rel', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('trade_user_rel', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('watchlist_user_rel', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_constraint('watchlist_user_rel', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_constraint('trade_user_rel', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('strategy', schema=None) as batch_op:
        batch_op.drop_constraint('strategy_user_rel', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.drop_constraint('setting_user_rel', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('error', schema=None) as batch_op:
        batch_op.drop_constraint('error_user_rel', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.drop_constraint('balance_user_rel', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
