"""Added ECN fee to the trade

Revision ID: b9fa184ee37f
Revises: 76c6ed2ba817
Create Date: 2025-11-25 14:44:33.779130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9fa184ee37f'
down_revision = '76c6ed2ba817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ecn_fee', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_column('ecn_fee')

    # ### end Alembic commands ###
